### ISSUE TITLE
scikit-learn-intelx is locking the version of scikit-learn

### ISSUE THREAD

**Issue by glemaitre** [conda-forge/scikit-learn-intelex-feedstock#21]
### Comment:

Trying my luck here. This issue is linked to: https://github.com/ContinuumIO/anaconda-issues/issues/13085

Since the `conda-forge` feedstock is pinning scikit-learn `<1.1`. However, this version is pretty old. We are going to release 1.2 in the next few weeks (the RC was released today).

Not keeping up-to-date the feedstock or `scikit-learn-intelx` is not really a big deal on its own but since the package is delivered in the Anaconda distribution, our users get stuck with an old version.

It could be nice to keep the project up-to-date or opt-out of the Anaconda distribution.

**Comment by napetrov** [comment]
Work in progress - deploying dal packages, then daal4py, then scikit extension.

https://github.com/conda-forge/intel_repack-feedstock/pull/37

**Comment by glemaitre** [comment]
Thanks @napetrov

**Comment by Alexsandruss** [comment]
2021.7.1 version was released without `<1.1` restriction for scikit-learn: https://anaconda.org/conda-forge/scikit-learn-intelex/files
